# Generated by Django 5.1.6 on 2025-02-15 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('frequence', models.CharField(choices=[('D', 'Diary'), ('1S', '1 time per week'), ('2S', '2 time per week'), ('3S', '3 time per week'), ('N', 'When needed')], default='D', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.PositiveIntegerField()),
                ('geral_registration', models.TextField()),
                ('video', models.FileField(upload_to='video')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patients')),
                ('tasks', models.ManyToManyField(to='patients.tasks')),
            ],
        ),
    ]
