# Generated by Django 5.1.6 on 2025-02-15 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_tasks_consultation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consultation',
            new_name='Consultations',
        ),
    ]
